# fly.toml app configuration file generated for lazernet-backend on 2025-08-27T16:57:12-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lazernet-backend'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
